spring:
  application:
    name: mustache
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://15.164.103.52:3306/todo
    username: todo
    password: 123
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      additional-exclude: static/**,templates/**
    livereload:
      enabled: true    
  mustache:
    charset: utf-8
server:
  servlet:
    encoding:
      force: true      
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml  
  type-aliases-package: com.example.member_post.vo
  configuration:
    map-underscore-to-camel-case: true